### PR TITLE
New logo! (again)

### LINKED ISSUE #101: Update the logo (again)
## Yes, this is me once again asking for the logo to be updated (pretty sure this is the last thing though).

Everytime Discord triggers an embed from Github, it shows this outdated version of the logo.

image

### This is the correct one that should be used. I swear I'll shut up about it :P 

MO-JIRA

### PR DESCRIPTION
**Pull request by dericksonmark**
Fixes #101. I used the image provided by LateLag on that issue. I left the old logo there because that was what was done when the logo was changed previously.

I would've used the pull request template, but I don't know what it means. :(

### CODE REVIEW

**Comment by dericksonmark** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by dericksonmark** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by dericksonmark** [comment]
**_I have read the CLA Document and I hereby sign the CLA_**

**Comment by NeunEinser** [comment]
Why not simply replace the old logo, instead of uploading a new file and keeping the old one?

**Comment by dericksonmark** [comment]
Hello! The last time the logo was replaced, the old file was kept. But I can just replace the old ones if you'd like.

**Review by chandler05 — APPROVED** [review]
Looks good! 👍

**Review by SPGoding — APPROVED** [review]
Seems like the integration cannot send comments for whatever reasons :thinking:

The CLA was signed correctly

**Comment by chandler05** [comment]
Just a GitHub actions bug because Mark isn't part of the Mojira organization. For some reason you can't sign the CLA unless you are a part of the repo's organization

**Pull request merged**
