### PR TITLE
Show an empty line in response message

### PR DESCRIPTION
**Pull request by SPGoding**

### CODE REVIEW

**Comment by chandler05** [comment]
Why use a period to create the empty line?

**Review by chandler05 — APPROVED** [review]

**Comment by SPGoding** [comment]
> 
> 
> Why use a period to create the empty line?

Because we need something to keep showing this line.

**Comment by Pokechu22** [comment]
What about a non-breaking space character (`&nbsp;`)?

**Comment by SPGoding** [comment]
Doesn't seem to work. Though I changed it to use hair space (` `) instead.

**Comment by Jack-McKalling** [comment]
Is this really necessary, for instance for mobile? Because I always already get a newline. Just triple-click to select the full line (including newline feed) and drag to select both lines. On mobile you can't click, so we really need a "Copy to clipboard" button

**Comment by violine1101** [comment]
Hmm, well personally I never had an issue with the line break on that message, I use the same technique as Jack to copy the message.

The issue with this fix is that it adds an additional zero width space character that you might not want to have in your message, you'd need to delete it every time.

**Comment by SPGoding** [comment]
I got used to Jack's method as well, so I guess we could just close this lol.

**Pull request closed without merging**
