### PR TITLE
Add CLA

### PR DESCRIPTION
**Pull request by violine1101**
Adds a CLA, similar to the one from arisa-kt.

### CODE REVIEW

**Comment by violine1101** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by urielsalis** [comment]
It's better to create a separate one

**Comment by NeunEinser** [comment]
You can't create 2 branches with the same name.

**Comment by violine1101** [comment]
Oops, wasn't aware that `cla` is the exact branch name that's needed for the cla storage.

I guess I should reopen this pr on another branch with a different name, so that the `cla` branch can be used separately?

**Comment by urielsalis** [comment]
Can be merged, deleted and a new branch created as long as no commit or
other branch is created before

**Pull request merged**
